[compiler.solc]
ignore_paths = ["node_modules", ".woke-build", "venv", "lib"]
include_paths = ["node_modules"]
remappings = [
    "@solady/=lib/solady/src/",
    "@solmate/=lib/solmate/src/",
    "@openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    "@src/=src/",
    "@src/libs/=src/libs/",
    "@forge-std/=lib/forge-std/src/",
    "@forge-gas-snapshot/=lib/forge-gas-snapshot/src/",
    "@crytic/properties/=lib/properties/src/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "ERC4626/=lib/properties/lib/ERC4626/contracts/",
    "aave-v3-core/=lib/aave-v3-core/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "erc4626-tests/=lib/openzeppelin-contracts-upgradeable/lib/erc4626-tests/",
    "erc721m/=lib/erc721m/contracts/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "forge-gas-snapshot/=lib/forge-gas-snapshot/src/",
    "forge-std/=lib/forge-std/src/",
    "hardhat-deploy/=node_modules/hardhat-deploy/",
    "hardhat/=node_modules/hardhat/",
    "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "openzeppelin/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "properties/=lib/properties/contracts/",
    "solady/=lib/solady/",
    "solmate/=lib/solmate/src/",
]

[compiler.solc.optimizer]
enabled = true
runs = 200

[detectors]
exclude = []
ignore_paths = ["node_modules", ".woke-build", "venv", "lib"]

[testing]
cmd = "anvil"

[testing.anvil]
cmd_args = "--prune-history 100 --transaction-block-keeper 10 --steps-tracing --silent"

[testing.ganache]
cmd_args = "-k istanbul -q"

[testing.hardhat]
cmd_args = ""