/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type CollectionStruct = {
  name: string;
  symbol: string;
  baseURI: string;
  baseExt: string;
  maxSupply: BigNumberish;
  royaltyFee: BigNumberish;
  royaltyReceiver: AddressLike;
};

export type CollectionStructOutput = [
  name: string,
  symbol: string,
  baseURI: string,
  baseExt: string,
  maxSupply: bigint,
  royaltyFee: bigint,
  royaltyReceiver: string
] & {
  name: string;
  symbol: string;
  baseURI: string;
  baseExt: string;
  maxSupply: bigint;
  royaltyFee: bigint;
  royaltyReceiver: string;
};

export type StagesStruct = {
  ogMintPrice: BigNumberish;
  whitelistMintPrice: BigNumberish;
  mintPrice: BigNumberish;
  mintMaxPerUser: BigNumberish;
  ogMintMaxPerUser: BigNumberish;
  whitelistMintMaxPerUser: BigNumberish;
  mintStart: BigNumberish;
  mintEnd: BigNumberish;
  ogMintStart: BigNumberish;
  ogMintEnd: BigNumberish;
  whitelistMintStart: BigNumberish;
  whitelistMintEnd: BigNumberish;
};

export type StagesStructOutput = [
  ogMintPrice: bigint,
  whitelistMintPrice: bigint,
  mintPrice: bigint,
  mintMaxPerUser: bigint,
  ogMintMaxPerUser: bigint,
  whitelistMintMaxPerUser: bigint,
  mintStart: bigint,
  mintEnd: bigint,
  ogMintStart: bigint,
  ogMintEnd: bigint,
  whitelistMintStart: bigint,
  whitelistMintEnd: bigint
] & {
  ogMintPrice: bigint;
  whitelistMintPrice: bigint;
  mintPrice: bigint;
  mintMaxPerUser: bigint;
  ogMintMaxPerUser: bigint;
  whitelistMintMaxPerUser: bigint;
  mintStart: bigint;
  mintEnd: bigint;
  ogMintStart: bigint;
  ogMintEnd: bigint;
  whitelistMintStart: bigint;
  whitelistMintEnd: bigint;
};

export interface MvxCollectionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "OG_MINTER_ROLE"
      | "OPERATOR_ROLE"
      | "WL_MINTER_ROLE"
      | "_feeDenominator"
      | "approve"
      | "balanceOf"
      | "baseURI"
      | "burn"
      | "collectionData"
      | "getApproved"
      | "getMintCountOf"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "isApprovedForAll"
      | "mintForOG"
      | "mintForOwner"
      | "mintForRegular"
      | "mintForWhitelist"
      | "mintingStages"
      | "mintsPerWallet"
      | "name"
      | "ownerOf"
      | "renounceRole"
      | "revokeRole"
      | "royaltyInfo"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setBaseExtension"
      | "setBaseURI"
      | "supportsInterface"
      | "symbol"
      | "tokenURI"
      | "totalSupply"
      | "transferFrom"
      | "updateMintMax"
      | "updateMintPrice"
      | "updateMinterRoles"
      | "updateOGMintMax"
      | "updateOGMintPrice"
      | "updateRoyaltyInfo"
      | "updateTime"
      | "updateWLMintMax"
      | "updateWhitelistMintPrice"
      | "version"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "BurnEvent"
      | "ConsecutiveTransfer"
      | "Log"
      | "MintEvent"
      | "OGmintEvent"
      | "OwnerMintEvent"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "RoyaltyFeeUpdate"
      | "Transfer"
      | "UpdateOgEvent"
      | "UpdateWLevent"
      | "WLmintEvent"
      | "WithdrawEvent"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OG_MINTER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WL_MINTER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_feeDenominator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "baseURI", values?: undefined): string;
  encodeFunctionData(functionFragment: "burn", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "collectionData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMintCountOf",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      BigNumberish,
      CollectionStruct,
      StagesStruct,
      AddressLike[],
      AddressLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintForOG",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintForOwner",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintForRegular",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintForWhitelist",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintingStages",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintsPerWallet",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "royaltyInfo",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseExtension",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setBaseURI", values: [string]): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMintMax",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMintPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMinterRoles",
    values: [AddressLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOGMintMax",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOGMintPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRoyaltyInfo",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTime",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWLMintMax",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWhitelistMintPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OG_MINTER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WL_MINTER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_feeDenominator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "baseURI", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectionData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMintCountOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintForOG", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintForOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintForRegular",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintForWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintingStages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintsPerWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "royaltyInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBaseExtension",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBaseURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMintMax",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMintPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMinterRoles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOGMintMax",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOGMintPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRoyaltyInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateWLMintMax",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWhitelistMintPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BurnEventEvent {
  export type InputTuple = [sender: AddressLike, tokenId: BigNumberish];
  export type OutputTuple = [sender: string, tokenId: bigint];
  export interface OutputObject {
    sender: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConsecutiveTransferEvent {
  export type InputTuple = [
    fromTokenId: BigNumberish,
    toTokenId: BigNumberish,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [
    fromTokenId: bigint,
    toTokenId: bigint,
    from: string,
    to: string
  ];
  export interface OutputObject {
    fromTokenId: bigint;
    toTokenId: bigint;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LogEvent {
  export type InputTuple = [arg0: string, arg1: BigNumberish];
  export type OutputTuple = [arg0: string, arg1: bigint];
  export interface OutputObject {
    arg0: string;
    arg1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintEventEvent {
  export type InputTuple = [
    sender: AddressLike,
    value: BigNumberish,
    to: AddressLike,
    amount: BigNumberish,
    mintPrice: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    value: bigint,
    to: string,
    amount: bigint,
    mintPrice: bigint
  ];
  export interface OutputObject {
    sender: string;
    value: bigint;
    to: string;
    amount: bigint;
    mintPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OGmintEventEvent {
  export type InputTuple = [
    sender: AddressLike,
    value: BigNumberish,
    to: AddressLike,
    amount: BigNumberish,
    _ogMintPrice: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    value: bigint,
    to: string,
    amount: bigint,
    _ogMintPrice: bigint
  ];
  export interface OutputObject {
    sender: string;
    value: bigint;
    to: string;
    amount: bigint;
    _ogMintPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnerMintEventEvent {
  export type InputTuple = [
    sender: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [sender: string, to: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoyaltyFeeUpdateEvent {
  export type InputTuple = [
    sender: AddressLike,
    receiver: AddressLike,
    royaltyFee: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    receiver: string,
    royaltyFee: bigint
  ];
  export interface OutputObject {
    sender: string;
    receiver: string;
    royaltyFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateOgEventEvent {
  export type InputTuple = [sender: AddressLike, listLength: BigNumberish];
  export type OutputTuple = [sender: string, listLength: bigint];
  export interface OutputObject {
    sender: string;
    listLength: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateWLeventEvent {
  export type InputTuple = [sender: AddressLike, listLength: BigNumberish];
  export type OutputTuple = [sender: string, listLength: bigint];
  export interface OutputObject {
    sender: string;
    listLength: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WLmintEventEvent {
  export type InputTuple = [
    sender: AddressLike,
    value: BigNumberish,
    to: AddressLike,
    amount: BigNumberish,
    wlMintPrice: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    value: bigint,
    to: string,
    amount: bigint,
    wlMintPrice: bigint
  ];
  export interface OutputObject {
    sender: string;
    value: bigint;
    to: string;
    amount: bigint;
    wlMintPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawEventEvent {
  export type InputTuple = [
    arg0: AddressLike,
    arg1: BigNumberish,
    arg2: AddressLike,
    arg3: BigNumberish
  ];
  export type OutputTuple = [
    arg0: string,
    arg1: bigint,
    arg2: string,
    arg3: bigint
  ];
  export interface OutputObject {
    arg0: string;
    arg1: bigint;
    arg2: string;
    arg3: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MvxCollection extends BaseContract {
  connect(runner?: ContractRunner | null): MvxCollection;
  waitForDeployment(): Promise<this>;

  interface: MvxCollectionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  OG_MINTER_ROLE: TypedContractMethod<[], [string], "view">;

  OPERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  WL_MINTER_ROLE: TypedContractMethod<[], [string], "view">;

  _feeDenominator: TypedContractMethod<[], [bigint], "view">;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "payable"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  baseURI: TypedContractMethod<[], [string], "view">;

  burn: TypedContractMethod<[_tokenId: BigNumberish], [void], "nonpayable">;

  collectionData: TypedContractMethod<
    [],
    [
      [string, string, string, string, bigint, bigint, string] & {
        name: string;
        symbol: string;
        baseURI: string;
        baseExt: string;
        maxSupply: bigint;
        royaltyFee: bigint;
        royaltyReceiver: string;
      }
    ],
    "view"
  >;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getMintCountOf: TypedContractMethod<
    [mintType: string, _user: AddressLike],
    [bigint],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      platformFee: BigNumberish,
      _nftData: CollectionStruct,
      _mintingStages: StagesStruct,
      _ogs: AddressLike[],
      _wls: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  mintForOG: TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "payable"
  >;

  mintForOwner: TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "payable"
  >;

  mintForRegular: TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "payable"
  >;

  mintForWhitelist: TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "payable"
  >;

  mintingStages: TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        ogMintPrice: bigint;
        whitelistMintPrice: bigint;
        mintPrice: bigint;
        mintMaxPerUser: bigint;
        ogMintMaxPerUser: bigint;
        whitelistMintMaxPerUser: bigint;
        mintStart: bigint;
        mintEnd: bigint;
        ogMintStart: bigint;
        ogMintEnd: bigint;
        whitelistMintStart: bigint;
        whitelistMintEnd: bigint;
      }
    ],
    "view"
  >;

  mintsPerWallet: TypedContractMethod<
    [arg0: AddressLike, arg1: string],
    [bigint],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  royaltyInfo: TypedContractMethod<
    [tokenId: BigNumberish, _salePrice: BigNumberish],
    [[string, bigint]],
    "view"
  >;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "payable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "payable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setBaseExtension: TypedContractMethod<
    [_newBaseExtension: string],
    [void],
    "nonpayable"
  >;

  setBaseURI: TypedContractMethod<[_newBaseURI: string], [void], "nonpayable">;

  supportsInterface: TypedContractMethod<
    [_interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenURI: TypedContractMethod<[_tokenId: BigNumberish], [string], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "payable"
  >;

  updateMintMax: TypedContractMethod<
    [_mintMax: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateMintPrice: TypedContractMethod<
    [_mintPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateMinterRoles: TypedContractMethod<
    [_minterList: AddressLike[], _mintRole: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateOGMintMax: TypedContractMethod<
    [_ogMintMax: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateOGMintPrice: TypedContractMethod<
    [_price: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateRoyaltyInfo: TypedContractMethod<
    [_receiver: AddressLike, _royaltyFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateTime: TypedContractMethod<
    [_start: BigNumberish, _end: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateWLMintMax: TypedContractMethod<
    [_whitelistMintMax: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateWhitelistMintPrice: TypedContractMethod<
    [_whitelistMintPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  version: TypedContractMethod<[], [bigint], "view">;

  withdraw: TypedContractMethod<[], [void], "payable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OG_MINTER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OPERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "WL_MINTER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "_feeDenominator"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "baseURI"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<[_tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "collectionData"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string, bigint, bigint, string] & {
        name: string;
        symbol: string;
        baseURI: string;
        baseExt: string;
        maxSupply: bigint;
        royaltyFee: bigint;
        royaltyReceiver: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getMintCountOf"
  ): TypedContractMethod<
    [mintType: string, _user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      platformFee: BigNumberish,
      _nftData: CollectionStruct,
      _mintingStages: StagesStruct,
      _ogs: AddressLike[],
      _wls: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintForOG"
  ): TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "mintForOwner"
  ): TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "mintForRegular"
  ): TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "mintForWhitelist"
  ): TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "mintingStages"
  ): TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        ogMintPrice: bigint;
        whitelistMintPrice: bigint;
        mintPrice: bigint;
        mintMaxPerUser: bigint;
        ogMintMaxPerUser: bigint;
        whitelistMintMaxPerUser: bigint;
        mintStart: bigint;
        mintEnd: bigint;
        ogMintStart: bigint;
        ogMintEnd: bigint;
        whitelistMintStart: bigint;
        whitelistMintEnd: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintsPerWallet"
  ): TypedContractMethod<[arg0: AddressLike, arg1: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "royaltyInfo"
  ): TypedContractMethod<
    [tokenId: BigNumberish, _salePrice: BigNumberish],
    [[string, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBaseExtension"
  ): TypedContractMethod<[_newBaseExtension: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBaseURI"
  ): TypedContractMethod<[_newBaseURI: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[_interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[_tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "updateMintMax"
  ): TypedContractMethod<[_mintMax: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateMintPrice"
  ): TypedContractMethod<[_mintPrice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateMinterRoles"
  ): TypedContractMethod<
    [_minterList: AddressLike[], _mintRole: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateOGMintMax"
  ): TypedContractMethod<[_ogMintMax: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateOGMintPrice"
  ): TypedContractMethod<[_price: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRoyaltyInfo"
  ): TypedContractMethod<
    [_receiver: AddressLike, _royaltyFee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateTime"
  ): TypedContractMethod<
    [_start: BigNumberish, _end: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateWLMintMax"
  ): TypedContractMethod<
    [_whitelistMintMax: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateWhitelistMintPrice"
  ): TypedContractMethod<
    [_whitelistMintPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "payable">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "BurnEvent"
  ): TypedContractEvent<
    BurnEventEvent.InputTuple,
    BurnEventEvent.OutputTuple,
    BurnEventEvent.OutputObject
  >;
  getEvent(
    key: "ConsecutiveTransfer"
  ): TypedContractEvent<
    ConsecutiveTransferEvent.InputTuple,
    ConsecutiveTransferEvent.OutputTuple,
    ConsecutiveTransferEvent.OutputObject
  >;
  getEvent(
    key: "Log"
  ): TypedContractEvent<
    LogEvent.InputTuple,
    LogEvent.OutputTuple,
    LogEvent.OutputObject
  >;
  getEvent(
    key: "MintEvent"
  ): TypedContractEvent<
    MintEventEvent.InputTuple,
    MintEventEvent.OutputTuple,
    MintEventEvent.OutputObject
  >;
  getEvent(
    key: "OGmintEvent"
  ): TypedContractEvent<
    OGmintEventEvent.InputTuple,
    OGmintEventEvent.OutputTuple,
    OGmintEventEvent.OutputObject
  >;
  getEvent(
    key: "OwnerMintEvent"
  ): TypedContractEvent<
    OwnerMintEventEvent.InputTuple,
    OwnerMintEventEvent.OutputTuple,
    OwnerMintEventEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RoyaltyFeeUpdate"
  ): TypedContractEvent<
    RoyaltyFeeUpdateEvent.InputTuple,
    RoyaltyFeeUpdateEvent.OutputTuple,
    RoyaltyFeeUpdateEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "UpdateOgEvent"
  ): TypedContractEvent<
    UpdateOgEventEvent.InputTuple,
    UpdateOgEventEvent.OutputTuple,
    UpdateOgEventEvent.OutputObject
  >;
  getEvent(
    key: "UpdateWLevent"
  ): TypedContractEvent<
    UpdateWLeventEvent.InputTuple,
    UpdateWLeventEvent.OutputTuple,
    UpdateWLeventEvent.OutputObject
  >;
  getEvent(
    key: "WLmintEvent"
  ): TypedContractEvent<
    WLmintEventEvent.InputTuple,
    WLmintEventEvent.OutputTuple,
    WLmintEventEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawEvent"
  ): TypedContractEvent<
    WithdrawEventEvent.InputTuple,
    WithdrawEventEvent.OutputTuple,
    WithdrawEventEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "BurnEvent(address,uint256)": TypedContractEvent<
      BurnEventEvent.InputTuple,
      BurnEventEvent.OutputTuple,
      BurnEventEvent.OutputObject
    >;
    BurnEvent: TypedContractEvent<
      BurnEventEvent.InputTuple,
      BurnEventEvent.OutputTuple,
      BurnEventEvent.OutputObject
    >;

    "ConsecutiveTransfer(uint256,uint256,address,address)": TypedContractEvent<
      ConsecutiveTransferEvent.InputTuple,
      ConsecutiveTransferEvent.OutputTuple,
      ConsecutiveTransferEvent.OutputObject
    >;
    ConsecutiveTransfer: TypedContractEvent<
      ConsecutiveTransferEvent.InputTuple,
      ConsecutiveTransferEvent.OutputTuple,
      ConsecutiveTransferEvent.OutputObject
    >;

    "Log(string,uint256)": TypedContractEvent<
      LogEvent.InputTuple,
      LogEvent.OutputTuple,
      LogEvent.OutputObject
    >;
    Log: TypedContractEvent<
      LogEvent.InputTuple,
      LogEvent.OutputTuple,
      LogEvent.OutputObject
    >;

    "MintEvent(address,uint256,address,uint256,uint256)": TypedContractEvent<
      MintEventEvent.InputTuple,
      MintEventEvent.OutputTuple,
      MintEventEvent.OutputObject
    >;
    MintEvent: TypedContractEvent<
      MintEventEvent.InputTuple,
      MintEventEvent.OutputTuple,
      MintEventEvent.OutputObject
    >;

    "OGmintEvent(address,uint256,address,uint256,uint256)": TypedContractEvent<
      OGmintEventEvent.InputTuple,
      OGmintEventEvent.OutputTuple,
      OGmintEventEvent.OutputObject
    >;
    OGmintEvent: TypedContractEvent<
      OGmintEventEvent.InputTuple,
      OGmintEventEvent.OutputTuple,
      OGmintEventEvent.OutputObject
    >;

    "OwnerMintEvent(address,address,uint256)": TypedContractEvent<
      OwnerMintEventEvent.InputTuple,
      OwnerMintEventEvent.OutputTuple,
      OwnerMintEventEvent.OutputObject
    >;
    OwnerMintEvent: TypedContractEvent<
      OwnerMintEventEvent.InputTuple,
      OwnerMintEventEvent.OutputTuple,
      OwnerMintEventEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "RoyaltyFeeUpdate(address,address,uint96)": TypedContractEvent<
      RoyaltyFeeUpdateEvent.InputTuple,
      RoyaltyFeeUpdateEvent.OutputTuple,
      RoyaltyFeeUpdateEvent.OutputObject
    >;
    RoyaltyFeeUpdate: TypedContractEvent<
      RoyaltyFeeUpdateEvent.InputTuple,
      RoyaltyFeeUpdateEvent.OutputTuple,
      RoyaltyFeeUpdateEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "UpdateOgEvent(address,uint256)": TypedContractEvent<
      UpdateOgEventEvent.InputTuple,
      UpdateOgEventEvent.OutputTuple,
      UpdateOgEventEvent.OutputObject
    >;
    UpdateOgEvent: TypedContractEvent<
      UpdateOgEventEvent.InputTuple,
      UpdateOgEventEvent.OutputTuple,
      UpdateOgEventEvent.OutputObject
    >;

    "UpdateWLevent(address,uint256)": TypedContractEvent<
      UpdateWLeventEvent.InputTuple,
      UpdateWLeventEvent.OutputTuple,
      UpdateWLeventEvent.OutputObject
    >;
    UpdateWLevent: TypedContractEvent<
      UpdateWLeventEvent.InputTuple,
      UpdateWLeventEvent.OutputTuple,
      UpdateWLeventEvent.OutputObject
    >;

    "WLmintEvent(address,uint256,address,uint256,uint256)": TypedContractEvent<
      WLmintEventEvent.InputTuple,
      WLmintEventEvent.OutputTuple,
      WLmintEventEvent.OutputObject
    >;
    WLmintEvent: TypedContractEvent<
      WLmintEventEvent.InputTuple,
      WLmintEventEvent.OutputTuple,
      WLmintEventEvent.OutputObject
    >;

    "WithdrawEvent(address,uint256,address,uint256)": TypedContractEvent<
      WithdrawEventEvent.InputTuple,
      WithdrawEventEvent.OutputTuple,
      WithdrawEventEvent.OutputObject
    >;
    WithdrawEvent: TypedContractEvent<
      WithdrawEventEvent.InputTuple,
      WithdrawEventEvent.OutputTuple,
      WithdrawEventEvent.OutputObject
    >;
  };
}
