/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type CollectionStruct = {
  name: string;
  symbol: string;
  baseURI: string;
  baseExt: string;
  maxSupply: BigNumberish;
  royaltyFee: BigNumberish;
  royaltyReceiver: AddressLike;
};

export type CollectionStructOutput = [
  name: string,
  symbol: string,
  baseURI: string,
  baseExt: string,
  maxSupply: bigint,
  royaltyFee: bigint,
  royaltyReceiver: string
] & {
  name: string;
  symbol: string;
  baseURI: string;
  baseExt: string;
  maxSupply: bigint;
  royaltyFee: bigint;
  royaltyReceiver: string;
};

export type StagesStruct = {
  ogMintPrice: BigNumberish;
  whitelistMintPrice: BigNumberish;
  mintPrice: BigNumberish;
  mintMaxPerUser: BigNumberish;
  ogMintMaxPerUser: BigNumberish;
  whitelistMintMaxPerUser: BigNumberish;
  mintStart: BigNumberish;
  mintEnd: BigNumberish;
  ogMintStart: BigNumberish;
  ogMintEnd: BigNumberish;
  whitelistMintStart: BigNumberish;
  whitelistMintEnd: BigNumberish;
};

export type StagesStructOutput = [
  ogMintPrice: bigint,
  whitelistMintPrice: bigint,
  mintPrice: bigint,
  mintMaxPerUser: bigint,
  ogMintMaxPerUser: bigint,
  whitelistMintMaxPerUser: bigint,
  mintStart: bigint,
  mintEnd: bigint,
  ogMintStart: bigint,
  ogMintEnd: bigint,
  whitelistMintStart: bigint,
  whitelistMintEnd: bigint
] & {
  ogMintPrice: bigint;
  whitelistMintPrice: bigint;
  mintPrice: bigint;
  mintMaxPerUser: bigint;
  ogMintMaxPerUser: bigint;
  whitelistMintMaxPerUser: bigint;
  mintStart: bigint;
  mintEnd: bigint;
  ogMintStart: bigint;
  ogMintEnd: bigint;
  whitelistMintStart: bigint;
  whitelistMintEnd: bigint;
};

export interface MvxFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "artists"
      | "collectionCount"
      | "collectionImpl"
      | "createCollection"
      | "deleteArtist"
      | "deleteMember"
      | "deployFee"
      | "getPartnerBalance"
      | "getReferralBalance"
      | "getTime()"
      | "getTime(uint256)"
      | "grantReferral"
      | "members"
      | "owner"
      | "partners"
      | "platformFee"
      | "renounceOwnership"
      | "totalCollections"
      | "transferOwnership"
      | "updateCollectionImpl"
      | "updateDeployFee"
      | "updateMember"
      | "updatePartnership"
      | "updatePlatformFee"
      | "withdraw"
      | "withdrawPartner"
      | "withdrawReferral"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CollectionDiscount"
      | "CreateCollectionEvent"
      | "CreateEvent"
      | "InitCollectionEvent"
      | "Log(string,uint256)"
      | "Log(string,bool)"
      | "OwnershipTransferred"
      | "PartnerBalanceUpdate"
      | "ReferralBalanceUpdate"
      | "ReferralDiscount"
      | "WithdrawPartner"
      | "WithdrawReferral"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "artists",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "collectionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collectionImpl",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createCollection",
    values: [CollectionStruct, StagesStruct, AddressLike[], AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteArtist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteMember",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "deployFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getPartnerBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReferralBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getTime()", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTime(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantReferral",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "members",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "partners",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalCollections",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCollectionImpl",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDeployFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMember",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePartnership",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawPartner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawReferral",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "artists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectionImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteArtist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deployFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPartnerBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReferralBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTime()", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTime(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantReferral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "members", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "partners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCollections",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCollectionImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDeployFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePartnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPartner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawReferral",
    data: BytesLike
  ): Result;
}

export namespace CollectionDiscountEvent {
  export type InputTuple = [_collection: AddressLike, _discount: BigNumberish];
  export type OutputTuple = [_collection: string, _discount: bigint];
  export interface OutputObject {
    _collection: string;
    _discount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreateCollectionEventEvent {
  export type InputTuple = [
    sender: AddressLike,
    template: AddressLike,
    clone: AddressLike
  ];
  export type OutputTuple = [sender: string, template: string, clone: string];
  export interface OutputObject {
    sender: string;
    template: string;
    clone: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreateEventEvent {
  export type InputTuple = [
    sender: AddressLike,
    impl: AddressLike,
    cloneAddress: AddressLike
  ];
  export type OutputTuple = [
    sender: string,
    impl: string,
    cloneAddress: string
  ];
  export interface OutputObject {
    sender: string;
    impl: string;
    cloneAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitCollectionEventEvent {
  export type InputTuple = [sender: AddressLike, collection: AddressLike];
  export type OutputTuple = [sender: string, collection: string];
  export interface OutputObject {
    sender: string;
    collection: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace Log_string_uint256_Event {
  export type InputTuple = [arg0: string, arg1: BigNumberish];
  export type OutputTuple = [arg0: string, arg1: bigint];
  export interface OutputObject {
    arg0: string;
    arg1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace Log_string_bool_Event {
  export type InputTuple = [arg0: string, arg1: boolean];
  export type OutputTuple = [arg0: string, arg1: boolean];
  export interface OutputObject {
    arg0: string;
    arg1: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PartnerBalanceUpdateEvent {
  export type InputTuple = [arg0: AddressLike, arg1: BigNumberish];
  export type OutputTuple = [arg0: string, arg1: bigint];
  export interface OutputObject {
    arg0: string;
    arg1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralBalanceUpdateEvent {
  export type InputTuple = [arg0: AddressLike, arg1: BigNumberish];
  export type OutputTuple = [arg0: string, arg1: bigint];
  export interface OutputObject {
    arg0: string;
    arg1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralDiscountEvent {
  export type InputTuple = [
    _artist: AddressLike,
    _sender: AddressLike,
    _collection: AddressLike
  ];
  export type OutputTuple = [
    _artist: string,
    _sender: string,
    _collection: string
  ];
  export interface OutputObject {
    _artist: string;
    _sender: string;
    _collection: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawPartnerEvent {
  export type InputTuple = [
    _sender: AddressLike,
    _collection: AddressLike,
    _balance: BigNumberish
  ];
  export type OutputTuple = [
    _sender: string,
    _collection: string,
    _balance: bigint
  ];
  export interface OutputObject {
    _sender: string;
    _collection: string;
    _balance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawReferralEvent {
  export type InputTuple = [
    _sender: AddressLike,
    _artist: AddressLike,
    _referralBalance: BigNumberish
  ];
  export type OutputTuple = [
    _sender: string,
    _artist: string,
    _referralBalance: bigint
  ];
  export interface OutputObject {
    _sender: string;
    _artist: string;
    _referralBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MvxFactory extends BaseContract {
  connect(runner?: ContractRunner | null): MvxFactory;
  waitForDeployment(): Promise<this>;

  interface: MvxFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  artists: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, string, bigint] & {
        referral: string;
        referralBalance: bigint;
        collection: string;
        expiration: bigint;
      }
    ],
    "view"
  >;

  collectionCount: TypedContractMethod<[], [bigint], "view">;

  collectionImpl: TypedContractMethod<[], [string], "view">;

  createCollection: TypedContractMethod<
    [
      _nftsData: CollectionStruct,
      _mintingStages: StagesStruct,
      _ogs: AddressLike[],
      _wls: AddressLike[]
    ],
    [string],
    "payable"
  >;

  deleteArtist: TypedContractMethod<
    [_artist: AddressLike],
    [void],
    "nonpayable"
  >;

  deleteMember: TypedContractMethod<
    [_member: AddressLike],
    [void],
    "nonpayable"
  >;

  deployFee: TypedContractMethod<[], [bigint], "view">;

  getPartnerBalance: TypedContractMethod<
    [_collection: AddressLike],
    [bigint],
    "view"
  >;

  getReferralBalance: TypedContractMethod<
    [_artist: AddressLike],
    [bigint],
    "view"
  >;

  "getTime()": TypedContractMethod<[], [bigint], "view">;

  "getTime(uint256)": TypedContractMethod<
    [_daysFromNow: BigNumberish],
    [bigint],
    "view"
  >;

  grantReferral: TypedContractMethod<
    [_extCollection: AddressLike, _artist: AddressLike],
    [void],
    "nonpayable"
  >;

  members: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint] & {
        collection: string;
        discount: bigint;
        expiration: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  partners: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint] & {
        admin: string;
        adminOwnPercent: bigint;
        referralOwnPercent: bigint;
        balance: bigint;
        discount: bigint;
        expiration: bigint;
      }
    ],
    "view"
  >;

  platformFee: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  totalCollections: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateCollectionImpl: TypedContractMethod<
    [_impl: AddressLike],
    [void],
    "payable"
  >;

  updateDeployFee: TypedContractMethod<
    [_newFee: BigNumberish],
    [void],
    "payable"
  >;

  updateMember: TypedContractMethod<
    [
      _newMember: AddressLike,
      _collection: AddressLike,
      _discount: BigNumberish,
      _expirationDays: BigNumberish
    ],
    [void],
    "payable"
  >;

  updatePartnership: TypedContractMethod<
    [
      _collection: AddressLike,
      _admin: AddressLike,
      _adminOwnPercent: BigNumberish,
      _referralOwnPercent: BigNumberish,
      _discountPercent: BigNumberish,
      _expireDaysFromNow: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  updatePlatformFee: TypedContractMethod<
    [_fee: BigNumberish],
    [void],
    "payable"
  >;

  withdraw: TypedContractMethod<[], [void], "payable">;

  withdrawPartner: TypedContractMethod<
    [_collection: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawReferral: TypedContractMethod<
    [artist_: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "artists"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, string, bigint] & {
        referral: string;
        referralBalance: bigint;
        collection: string;
        expiration: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "collectionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "collectionImpl"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createCollection"
  ): TypedContractMethod<
    [
      _nftsData: CollectionStruct,
      _mintingStages: StagesStruct,
      _ogs: AddressLike[],
      _wls: AddressLike[]
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "deleteArtist"
  ): TypedContractMethod<[_artist: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteMember"
  ): TypedContractMethod<[_member: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deployFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPartnerBalance"
  ): TypedContractMethod<[_collection: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReferralBalance"
  ): TypedContractMethod<[_artist: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTime()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTime(uint256)"
  ): TypedContractMethod<[_daysFromNow: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantReferral"
  ): TypedContractMethod<
    [_extCollection: AddressLike, _artist: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "members"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint] & {
        collection: string;
        discount: bigint;
        expiration: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "partners"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint] & {
        admin: string;
        adminOwnPercent: bigint;
        referralOwnPercent: bigint;
        balance: bigint;
        discount: bigint;
        expiration: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "platformFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalCollections"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateCollectionImpl"
  ): TypedContractMethod<[_impl: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "updateDeployFee"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "updateMember"
  ): TypedContractMethod<
    [
      _newMember: AddressLike,
      _collection: AddressLike,
      _discount: BigNumberish,
      _expirationDays: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "updatePartnership"
  ): TypedContractMethod<
    [
      _collection: AddressLike,
      _admin: AddressLike,
      _adminOwnPercent: BigNumberish,
      _referralOwnPercent: BigNumberish,
      _discountPercent: BigNumberish,
      _expireDaysFromNow: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePlatformFee"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "withdrawPartner"
  ): TypedContractMethod<[_collection: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawReferral"
  ): TypedContractMethod<[artist_: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CollectionDiscount"
  ): TypedContractEvent<
    CollectionDiscountEvent.InputTuple,
    CollectionDiscountEvent.OutputTuple,
    CollectionDiscountEvent.OutputObject
  >;
  getEvent(
    key: "CreateCollectionEvent"
  ): TypedContractEvent<
    CreateCollectionEventEvent.InputTuple,
    CreateCollectionEventEvent.OutputTuple,
    CreateCollectionEventEvent.OutputObject
  >;
  getEvent(
    key: "CreateEvent"
  ): TypedContractEvent<
    CreateEventEvent.InputTuple,
    CreateEventEvent.OutputTuple,
    CreateEventEvent.OutputObject
  >;
  getEvent(
    key: "InitCollectionEvent"
  ): TypedContractEvent<
    InitCollectionEventEvent.InputTuple,
    InitCollectionEventEvent.OutputTuple,
    InitCollectionEventEvent.OutputObject
  >;
  getEvent(
    key: "Log(string,uint256)"
  ): TypedContractEvent<
    Log_string_uint256_Event.InputTuple,
    Log_string_uint256_Event.OutputTuple,
    Log_string_uint256_Event.OutputObject
  >;
  getEvent(
    key: "Log(string,bool)"
  ): TypedContractEvent<
    Log_string_bool_Event.InputTuple,
    Log_string_bool_Event.OutputTuple,
    Log_string_bool_Event.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PartnerBalanceUpdate"
  ): TypedContractEvent<
    PartnerBalanceUpdateEvent.InputTuple,
    PartnerBalanceUpdateEvent.OutputTuple,
    PartnerBalanceUpdateEvent.OutputObject
  >;
  getEvent(
    key: "ReferralBalanceUpdate"
  ): TypedContractEvent<
    ReferralBalanceUpdateEvent.InputTuple,
    ReferralBalanceUpdateEvent.OutputTuple,
    ReferralBalanceUpdateEvent.OutputObject
  >;
  getEvent(
    key: "ReferralDiscount"
  ): TypedContractEvent<
    ReferralDiscountEvent.InputTuple,
    ReferralDiscountEvent.OutputTuple,
    ReferralDiscountEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawPartner"
  ): TypedContractEvent<
    WithdrawPartnerEvent.InputTuple,
    WithdrawPartnerEvent.OutputTuple,
    WithdrawPartnerEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawReferral"
  ): TypedContractEvent<
    WithdrawReferralEvent.InputTuple,
    WithdrawReferralEvent.OutputTuple,
    WithdrawReferralEvent.OutputObject
  >;

  filters: {
    "CollectionDiscount(address,uint96)": TypedContractEvent<
      CollectionDiscountEvent.InputTuple,
      CollectionDiscountEvent.OutputTuple,
      CollectionDiscountEvent.OutputObject
    >;
    CollectionDiscount: TypedContractEvent<
      CollectionDiscountEvent.InputTuple,
      CollectionDiscountEvent.OutputTuple,
      CollectionDiscountEvent.OutputObject
    >;

    "CreateCollectionEvent(address,address,address)": TypedContractEvent<
      CreateCollectionEventEvent.InputTuple,
      CreateCollectionEventEvent.OutputTuple,
      CreateCollectionEventEvent.OutputObject
    >;
    CreateCollectionEvent: TypedContractEvent<
      CreateCollectionEventEvent.InputTuple,
      CreateCollectionEventEvent.OutputTuple,
      CreateCollectionEventEvent.OutputObject
    >;

    "CreateEvent(address,address,address)": TypedContractEvent<
      CreateEventEvent.InputTuple,
      CreateEventEvent.OutputTuple,
      CreateEventEvent.OutputObject
    >;
    CreateEvent: TypedContractEvent<
      CreateEventEvent.InputTuple,
      CreateEventEvent.OutputTuple,
      CreateEventEvent.OutputObject
    >;

    "InitCollectionEvent(address,address)": TypedContractEvent<
      InitCollectionEventEvent.InputTuple,
      InitCollectionEventEvent.OutputTuple,
      InitCollectionEventEvent.OutputObject
    >;
    InitCollectionEvent: TypedContractEvent<
      InitCollectionEventEvent.InputTuple,
      InitCollectionEventEvent.OutputTuple,
      InitCollectionEventEvent.OutputObject
    >;

    "Log(string,uint256)": TypedContractEvent<
      Log_string_uint256_Event.InputTuple,
      Log_string_uint256_Event.OutputTuple,
      Log_string_uint256_Event.OutputObject
    >;
    "Log(string,bool)": TypedContractEvent<
      Log_string_bool_Event.InputTuple,
      Log_string_bool_Event.OutputTuple,
      Log_string_bool_Event.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PartnerBalanceUpdate(address,uint256)": TypedContractEvent<
      PartnerBalanceUpdateEvent.InputTuple,
      PartnerBalanceUpdateEvent.OutputTuple,
      PartnerBalanceUpdateEvent.OutputObject
    >;
    PartnerBalanceUpdate: TypedContractEvent<
      PartnerBalanceUpdateEvent.InputTuple,
      PartnerBalanceUpdateEvent.OutputTuple,
      PartnerBalanceUpdateEvent.OutputObject
    >;

    "ReferralBalanceUpdate(address,uint256)": TypedContractEvent<
      ReferralBalanceUpdateEvent.InputTuple,
      ReferralBalanceUpdateEvent.OutputTuple,
      ReferralBalanceUpdateEvent.OutputObject
    >;
    ReferralBalanceUpdate: TypedContractEvent<
      ReferralBalanceUpdateEvent.InputTuple,
      ReferralBalanceUpdateEvent.OutputTuple,
      ReferralBalanceUpdateEvent.OutputObject
    >;

    "ReferralDiscount(address,address,address)": TypedContractEvent<
      ReferralDiscountEvent.InputTuple,
      ReferralDiscountEvent.OutputTuple,
      ReferralDiscountEvent.OutputObject
    >;
    ReferralDiscount: TypedContractEvent<
      ReferralDiscountEvent.InputTuple,
      ReferralDiscountEvent.OutputTuple,
      ReferralDiscountEvent.OutputObject
    >;

    "WithdrawPartner(address,address,uint256)": TypedContractEvent<
      WithdrawPartnerEvent.InputTuple,
      WithdrawPartnerEvent.OutputTuple,
      WithdrawPartnerEvent.OutputObject
    >;
    WithdrawPartner: TypedContractEvent<
      WithdrawPartnerEvent.InputTuple,
      WithdrawPartnerEvent.OutputTuple,
      WithdrawPartnerEvent.OutputObject
    >;

    "WithdrawReferral(address,address,uint256)": TypedContractEvent<
      WithdrawReferralEvent.InputTuple,
      WithdrawReferralEvent.OutputTuple,
      WithdrawReferralEvent.OutputObject
    >;
    WithdrawReferral: TypedContractEvent<
      WithdrawReferralEvent.InputTuple,
      WithdrawReferralEvent.OutputTuple,
      WithdrawReferralEvent.OutputObject
    >;
  };
}
