name: Smart Contract CI

on:
  push:
    branches:
      - dev-ci
  pull_request:
    branches:
      - dev-ci

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -y | sh

      - name: Install Foundry
        run: curl -L https://foundry.paradigm.xyz | bash
      
      - name: source foundry
        run: source /home/runner/.bashrc     

      - name: cat /home/runner/.bashrc     
        run: cat /home/runner/.bashrc

      - name: foundryup...
        run: foundryup

      - name: Install Tenderly CLI
        run: curl https://raw.githubusercontent.com/Tenderly/tenderly-cli/master/scripts/install-linux.sh | sudo sh

      - name: Run tests
        run: yarn run test
        working-directory: ./
        env:
          TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
          TENDERLY_PROJECT_SLUG: '???' # your project slug
          TENDERLY_DEVNET_TEMPLATE: '???' # your devnet template slug
          TENDERLY_ACCOUNT_ID: '???' # your username or organization name